spring.application.name=escola

spring.datasource.url=jdbc:postgresql://localhost:5432/escola
spring.datasource.username=escola
spring.datasource.password=escola

spring.modulith.events.jdbc.schema-initialization.enabled=true
spring.modulith.events.republish-outstanding-events-on-restart=true

spring.kafka.bootstrap-servers=localhost:9092
